### ISSUE TITLE
echo example should support polyfills

### ISSUE THREAD

**Issue by jkarneges** [fanout/websockhop#13]
Maybe add a dropdown box to select among WebSocket, SockJS, Engine.IO.

**Comment by harmony7** [comment]
oh, or maybe it's possible to make a folder that contains the example

**Comment by harmony7** [comment]
The echo example has been moved to a subdirectory inside the app so that it can have its own runtime node modules.

To run, switch to the examples/echo subdirectory and run install, then open the index.html file in a browser.
