### ISSUE TITLE
Recover after lost connection

### ISSUE THREAD

**Issue by xppt** [fanout/websockhop#20]
I wanted to check how WebSockHop will behave on connection lost and temporary added a blocking rule to my iptables list. After connection recover my handlers become repeatedly receiving events "opened", "message", "closed" with 10 seconds delay between sequences.

After some research I figured out that it is because of _lastSentPing property value, which was not cleaned up after initial connection.
Because of this and the transmitted data WebSockHop choose to extend delay of pong awaiting and to add request timeout, which eventually closed this stable connection. And it happens in a loop forever.

I think that _lastSentPing should be cleaned in case native socket was closed.

**Comment by gobengo** [comment]
Thanks for the heads up @xppt . I'm going to try to reproduce this and find a fix this week

**Comment by gobengo** [comment]
@xppt I was able to reproduce this bug and made a fix at PR #23 . Can you confirm that that branch solves the problem in your project?

**Comment by xppt** [comment]
Yea, it is working like expected now.
I am not absolutely sure because a week ago I observed one more weird behavior (with eventually disappeared pings) using quite similar fix to yours one, but today I failed to reproduce it even using my old code. So I'll let know if it will happen again.
Thank you very much!

**Comment by jkarneges** [comment]
Merged.
