### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by xppt** [fanout/websockhop#22]
Because of `mkdir -p` usage in the build scripts, websockhop is not building on Windows.
I think there should be used some crossplatform version, like mkdirp.

**Comment by gobengo** [comment]
@xppt I made #25 to switch to using `mkdirp`, but don't have access to a Windows box right now. Does it work for you? If so, are there any other downstream windows-only errors you see happen after the `mkdirp`?

**Comment by xppt** [comment]
Thanks!
It's working great now, and no mkdirp related errors happen on `issue-22` branch.

**Comment by jkarneges** [comment]
Merged.
