### ISSUE TITLE
allow substituting WebSocket class with SockJS or Engine.io

### ISSUE THREAD

**Issue by jkarneges** [fanout/websockhop#9]
SockJS and Engine.io are essentially polyfills for WebSocket that support polling in browsers that don't support WebSockets. We should make it possible to use these systems with WebSockHop if necessary.

Note that this should just be a simple substitution, using another class instead of `new WebSocket`. WebSockHop itself shouldn't manage many transports or do fallbacks or anything crazy like that.

**Comment by harmony7** [comment]
In d6c0820, code was added so that it's now possible to provide a custom createSocket function.

```javascript
import EngineIoSocket from "engine.io-as-websocket";

const wsh = new WebSockHop(uri, {
  createSocket: (url) => new EngineIoSocket(url)
});
```

The example uses engine.io-as-websocket (https://github.com/fanout/engine.io-as-websocket), but should work with any library that has the same (or close enough) API surface as WebSocket.
